config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get "/lfeleo-cv", to: "static_pages#cv", :as => 'cv'
  get "/lfeleo-projet-1ere-annee", to: "static_pages#project1st", :as => 'projet1'
  get "/lfeleo-projet-2eme-annee", to: "static_pages#project2nd", :as => 'projet2'
  get "/lfeleo-stage-1ere-annee", to: "static_pages#stage1st", :as => 'stage1'
  get "/lfeleo-stage-2eme-annee", to: "static_pages#stage2nd", :as => 'stage2'
  get "/lfeleo-veille-technologique", to: "static_pages#veille_techno", :as => 'techno'
  get "/lfeleo-veille-juridique", to: "static_pages#veille_juridique", :as => 'juri'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- footer -->
    <footer class="separator-top">
      <div class="container py-5">
        <div class="row justify-content-between align-items-center">
          <div class="col-md-5 text-center text-md-left">
            <ul class="nav">
              <li class="nav-item">
              <li><a class="icon-phone text-dark fs-30"></a> 06 38 45 59 86</li>
              <li><a href="mailto:laureane_feleo@hotmail.fr" class="icon-mail text-dark fs-30"></a>  laureane_feleo@hotmail.fr</li>
            </ul>
          </div>
          <div class="col-md-2 text-center">
            <a class="" href="<%=root_path%>">
            <img class="logo-sm" src="../../assets/lfeleo-logo.png" alt="Logo">
          </a>
          </div>
          <div class="col-md-5 text-center text-md-right">
            <ul class="socials">
              <li><a href="https://github.com/lfeleo" class="icon-github text-dark fs-30"></a></li>
              <li><a href="https://www.linkedin.com/in/laureane-feleo-281378185/" class="icon-linkedin text-dark fs-30"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- / footer -->

app/views/layouts/_navbar.html.erb
<!-- header -->
    <header class="header-sticky header-dark">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="<%=root_path%>">
            <img class="navbar-logo navbar-logo-light " src="../../assets/lfeleo-logo-light.png" alt="Logo">
            <img class="navbar-logo navbar-logo-dark" src="../../assets/lfeleo-logo.png" alt="Logo">
          </a>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation"><span class="burger"><span></span></span></button>

       
          <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
            <ul class="navbar-nav align-items-center mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="<%=root_path%>" role="button">
                  Accueil
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="<%=cv_path%>" role="button">
                Curriculum vitae
                </a>
              </li>

              <li class="nav-item dropdown ">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Stages
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<%=stage1_path%>">
                    <span>1ère année</span>
                    <p>CMLA</p>
                  </a>

                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="<%=stage2_path%>">
                    <span>2ème année</span>
                    <p>Cooodit</p>
                  </a>
              </li>


              <li class="nav-item dropdown dropdown-mega">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown-1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Projets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown-1">
                  <div class="row">
                    <div class="col">
                      <ul class="mega-list">
                        <li><a href="<%=projet1_path%>" class="highlight">Projet 1ère année</a></li>
                        
                      </ul>

                    </div>
                    <div class="col">
                      <ul class="mega-list">
                        <li><a href="<%=projet2_path%>">Projet 2ème année</a></li>
                      </ul>
                    </div>

              <li class="nav-item dropdown show">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Veilles
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<%=techno_path%>">
                    <span>Veille technologique</span>
                    <p>Réalité augmentée</p>
                  </a>

                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="<%=juri_path%>">
                    <span>Veille juridique</span>
                    <p></p>
                  </a>
              </li>

                    



                  </div>
                </div>
              </li>
            </ul>
            </ul>
        
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LFELEO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/project1st.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/images/demo/image-2.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Projets</b> 1ère année</h1>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/project2nd.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/images/demo/image-2.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Projets</b> 2ème année</h1>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/stage1st.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/cournotLaplace1.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Stage</b> 1ère année</h1>
      </div>
    </div>
  </div>
</section>



<section class="bg-white text-black"
      data-top-top="transform: translateY(0px);" 
      data-top-bottom="transform: translateY(200px);">
      <div class="container">
      <div class="row align-items-center">
          <div class="col-md-8 align-items-center ">


<h3>Outils utilisés</h3>
            <div class="container"
            <div class="bordered">
            <div class="row justify-content-between align-items-center text-center text-md-left">
               
                      <img src="../../assets/python_logo.png"/>
                      <img alt="phpstorm-logo"src="../../assets/docker_logo.png"/>
                      <img alt="phpstorm-logo"src="../../assets/sublime_text_logo.png"/>
                      <img alt="phpstorm-logo"src="../../assets/trello_logo.png"/>
                      
            </div>
            </div>
           
            </div>  
            
      </div>
</section>


<style>
img{
  height:50px;
  width:50px;
}
</style>

app/views/static_pages/stage2nd.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/images/demo/image-2.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Stage</b> 2ème année</h1>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/veille_juridique.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/images/demo/image-2.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Veille</b> juridique</h1>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/veille_techno.html.erb
<section class="text-white pattern skrollable skrollable-between" data-top-top="transform: translateY(0px);" 
data-top-bottom="transform: translateY(250px);" style="transform: translateY(16.8998px);">
<div class="image image-overlay" style="background-image:url(../../assets/images/demo/image-2.jpg)"></div>
  <div class="container pt-10">
    <div class="row mb-2 justify-content-center" >
      <div class="col-md-8 col-lg-6">
        <h1> <b>Veille</b> technologique</h1>
      </div>
    </div>
  </div>
</section>





<section class="bg-white text-black"
      data-top-top="transform: translateY(0px);" 
      data-top-bottom="transform: translateY(200px);">
      <div class="container">
      <div class="row align-items-center">
          <div class="col-md-12 align-items-center ">

            <p>
              La veille technologie consiste à s’informer en continu sur les nouveautés d’un secteur, les inventions des concurrents, 
              ainsi que des nouvelles technologies dans le but d’être le meilleur dans son domaine.
            </p>

            
      </div>
</section>
<style>
img{
  height:50px;
  width:50px;
}
</style>